# Generated by Django 5.2 on 2025-04-08 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('range', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipe',
            name='recipe_image',
            field=models.ImageField(blank=True, null=True, upload_to='recipes/'),
        ),
        migrations.AlterField(
            model_name='receipe',
            name='receipe_name',
            field=models.CharField(max_length=100),
        ),
    ]
