# Generated by Django 5.2 on 2025-04-08 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('range', '0002_receipe_recipe_image_alter_receipe_receipe_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipe',
            name='recipe_image',
            field=models.ImageField(blank=True, null=True, upload_to='receipe'),
        ),
    ]
