# Generated by Django 5.2 on 2025-04-08 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('range', '0003_alter_receipe_recipe_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipe',
            name='recipe_image',
            field=models.ImageField(blank=True, null=True, upload_to='receipe/'),
        ),
    ]
