# Generated by Django 5.2 on 2025-04-08 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('range', '0004_alter_receipe_recipe_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receipe',
            old_name='recipe_image',
            new_name='receipe_image',
        ),
    ]
